name = "idkaboutbytes/singleton"
version = "1.0.4"
description = "Singleton package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/singleton"
includes = ["pesde.toml", "README.md", "CHANGELOG.md", "default.project.json", "src/**/*.luau"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
ServiceBag = { repo = "idkaboutbytes/servicebag", rev = "v1.0.6" }
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.5" }
